[32m2025-01-23 11:03:29 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 99e32a5a-f61f-485f-9abb-1a16bc9d022a - 50967 - LOGS_CAPTURED - Started capturing logs in process (pid: 50967).
[32m2025-01-23 11:03:29 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 99e32a5a-f61f-485f-9abb-1a16bc9d022a - 50967 - dbt_analytics - STEP_START - Started execution of step "dbt_analytics".
[32m2025-01-23 11:03:29 -0600[0m - dagster - [34mINFO[0m - __ASSET_JOB - 99e32a5a-f61f-485f-9abb-1a16bc9d022a - dbt_analytics - A dbt subsetted execution is being performed. Overriding default dbt selection arguments `['--select', 'fqn:*']` with arguments: `['db_postgres.movies']`.
[32m2025-01-23 11:03:29 -0600[0m - dagster - [34mWARNING[0m - __ASSET_JOB - 99e32a5a-f61f-485f-9abb-1a16bc9d022a - dbt_analytics - An error was encountered when creating a handle to the dbt adapter in Dagster.
Traceback (most recent call last):
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dagster_dbt/core/resource.py", line 672, in cli
    adapter = self._initialize_adapter(cli_vars)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dagster_dbt/core/resource.py", line 364, in _initialize_adapter
    profile = load_profile(self.project_dir, cli_vars, self.profile, self.target)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dbt/config/runtime.py", line 71, in load_profile
    profile = Profile.render(
              ^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dbt/config/profile.py", line 403, in render
    return cls.from_raw_profiles(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ari/opt/miniconda3/envs/dagster-rs/lib/python3.12/site-packages/dbt/config/profile.py", line 360, in from_raw_profiles
    raise DbtProjectError("Could not find profile named '{}'".format(profile_name))
dbt.exceptions.DbtProjectError: Runtime Error
  Could not find profile named 'db_postgres'
[32m2025-01-23 11:03:29 -0600[0m - dagster - [34mINFO[0m - __ASSET_JOB - 99e32a5a-f61f-485f-9abb-1a16bc9d022a - dbt_analytics - Copying `/Users/ari/Desktop/github_repos/db_postgres/target/partial_parse.msgpack` to `/Users/ari/Desktop/github_repos/db_postgres/target/dbt_analytics-99e32a5-8de6042/partial_parse.msgpack` to take advantage of partial parsing.
[32m2025-01-23 11:03:29 -0600[0m - dagster - [34mINFO[0m - __ASSET_JOB - 99e32a5a-f61f-485f-9abb-1a16bc9d022a - dbt_analytics - Running dbt command: `dbt run --select db_postgres.movies`.
[32m2025-01-23 11:03:31 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 99e32a5a-f61f-485f-9abb-1a16bc9d022a - 50967 - dbt_analytics - STEP_OUTPUT - Yielded output "movies" of type "Nothing". (Type check passed).
[32m2025-01-23 11:03:31 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 99e32a5a-f61f-485f-9abb-1a16bc9d022a - 50967 - dbt_analytics - ASSET_MATERIALIZATION - Materialized value movies.
[32m2025-01-23 11:03:31 -0600[0m - dagster - [34mINFO[0m - __ASSET_JOB - 99e32a5a-f61f-485f-9abb-1a16bc9d022a - dbt_analytics - Finished dbt command: `dbt run --select db_postgres.movies`.
[32m2025-01-23 11:03:31 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 99e32a5a-f61f-485f-9abb-1a16bc9d022a - 50967 - dbt_analytics - STEP_SUCCESS - Finished execution of step "dbt_analytics" in 2.54s.
